{% set name = "cymove" %}
{% set version = "1.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ozars/cymove/archive/v{{ version }}.tar.gz
  sha256: bfc34c0d191154a4c76c878739edb525049e8aa5d1986b80a5bb651d894d2d00

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - cython

test:
  commands:
    - cp "${RECIPE_DIR}/cymove_example.pyx" .
    - cythonize -3 -i cymove_example.pyx
    - python3 -c "import cymove_example"
    - pip check
  requires:
    - pip
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

about:
  home: https://pypi.org/project/cymove/
  summary: std::move wrapper for cython
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/ozars/cymove
  doc_url: https://github.com/ozars/cymove/blob/master/README.md

extra:
  recipe-maintainers:
    - chrisburr
